site_name: My Docs
theme:
  name: material
  features:
    - content.footnote.tooltips
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
  
  color_mode: auto

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - mdx_truly_sane_lists

hooks:
  - docs_hooks.py

extra:
  version:
    prodiver: mike
    default: latest
