site_name: Adam Duvick
theme:
  name: material
  features:
    - content.footnote.tooltips
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
  
  color_mode: auto

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - mdx_truly_sane_lists

hooks:
  - docs_hooks.py

extra:
  version:
    prodiver: mike
    default: latest

nav:
  - Home:
    - "index.md"
    - "bacon-'n'-pasta-parmesan.md"
    - "baked-oatmeal.md"
    - "basic-sourdough.md"
    - "beer-bread.md"
    - "best-barbecue-beef-brisket.md"
    - "best-ground-beef-chili.md"
    - "breakfast-casserole.md"
    - "broccoli-salad.md"
    - "cantonese-style-black-pepper-beef-with-potatoes.md"
    - "carnitas-spice-mixture.md"
    - "carnitas.md"
    - "cheeseburger-soup.md"
    - "cherry-almond-amish-sugar-cookies.md"
    - "chicken-&-wild-rice-soup.md"
    - "chicken-and-broccoli-braid.md"
    - "chocolate-chip-cookies.md"
    - "chocolate-chip-tea-cakes.md"
    - "chocolate-doughnut-muffins.md"
    - "chocolate-logs.md"
    - "cinnamon-rolls.md"
    - "cold-brew.md"
    - "cracker-stuff.md"
    - "cream-scones.md"
    - "cuban-black-beans.md"
    - "curried-tuna-salad-with-apples-and-currants.md"
    - "delicate-lemon-squares.md"
    - "easy-chicken-divan.md"
    - "egg-wash.md"
    - "english-muffins.md"
    - "fluff-'n'-blueberries.md"
    - "garlic-parmesan-baked-halibut.md"
    - "gingerbread-cookies.md"
    - "gold-bars.md"
    - "granola.md"
    - "green-beans-with-caramelized-shallots.md"
    - "guacamole.md"
    - "ham-and-gruyere-egg-bites.md"
    - "healthy-yummy-no-bakes.md"
    - "homemade-ranch.md"
    - "italian-beef.md"
    - "japanese-coleslaw.md"
    - "jill’s-pretty-darn-good-white-chili.md"
    - "kim's-coleslaw.md"
    - "mary's-sloppy-joes.md"
    - "mississippi-roast.md"
    - "overnight-cinnamon-rolls.md"
    - "pasta-with-browned-butter.md"
    - "peanut-butter-bonbons.md"
    - "pumpkin-bars.md"
    - "roasted-broccoli.md"
    - "rolf’s-rumaki.md"
    - "slow-cooker-bbq-pulled-chicken.md"
    - "spaghetti-sauce.md"
    - "split-pea-soup.md"
    - "sticky-buns.md"
    - "tapioca-surprise.md"
    - "the-best-pulled-pork-ever.md"
    - "vanilla-sweet-cream.md"
    - "veggie-pizza.md"
    - "whip-cream-salad.md"
    - "white-chicken-chili.md"
    - "whole-wheat-bread.md"
    - "whole-wheat-rolls.md"