site_name: Adam Duvick
theme:
  name: material
  features:
    - content.footnote.tooltips
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
  
  color_mode: auto

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - mdx_truly_sane_lists

hooks:
  - docs_hooks.py

extra:
  version:
    prodiver: mike
    default: latest

nav:
  - Home:
    - 'index.md'
    - Games:
      - 'games/index.md'
      - 'games/shanghai.md'
      - 'games/texas-canasta.md'
    - Recipes:
      - 'recipes/index.md'
      - "recipes/bacon-'n'-pasta-parmesan.md"
      - "recipes/baked-oatmeal.md"
      - "recipes/basic-sourdough.md"
      - "recipes/beer-bread.md"
      - "recipes/best-barbecue-beef-brisket.md"
      - "recipes/best-ground-beef-chili.md"
      - "recipes/breakfast-casserole.md"
      - "recipes/broccoli-salad.md"
      - "recipes/cantonese-style-black-pepper-beef-with-potatoes.md"
      - "recipes/carnitas-spice-mixture.md"
      - "recipes/carnitas.md"
      - "recipes/cheeseburger-soup.md"
      - "recipes/cherry-almond-amish-sugar-cookies.md"
      - "recipes/chicken-&-wild-rice-soup.md"
      - "recipes/chicken-and-broccoli-braid.md"
      - "recipes/chocolate-chip-cookies.md"
      - "recipes/chocolate-chip-tea-cakes.md"
      - "recipes/chocolate-doughnut-muffins.md"
      - "recipes/chocolate-logs.md"
      - "recipes/cinnamon-rolls.md"
      - "recipes/cold-brew.md"
      - "recipes/cracker-stuff.md"
      - "recipes/cream-scones.md"
      - "recipes/cuban-black-beans.md"
      - "recipes/curried-tuna-salad-with-apples-and-currants.md"
      - "recipes/delicate-lemon-squares.md"
      - "recipes/easy-chicken-divan.md"
      - "recipes/egg-wash.md"
      - "recipes/english-muffins.md"
      - "recipes/fluff-'n'-blueberries.md"
      - "recipes/garlic-parmesan-baked-halibut.md"
      - "recipes/gingerbread-cookies.md"
      - "recipes/gold-bars.md"
      - "recipes/granola.md"
      - "recipes/green-beans-with-caramelized-shallots.md"
      - "recipes/guacamole.md"
      - "recipes/ham-and-gruyere-egg-bites.md"
      - "recipes/healthy-yummy-no-bakes.md"
      - "recipes/homemade-ranch.md"
      - "recipes/italian-beef.md"
      - "recipes/japanese-coleslaw.md"
      - "recipes/jill’s-pretty-darn-good-white-chili.md"
      - "recipes/kim's-coleslaw.md"
      - "recipes/mary's-sloppy-joes.md"
      - "recipes/mississippi-roast.md"
      - "recipes/overnight-cinnamon-rolls.md"
      - "recipes/pasta-with-browned-butter.md"
      - "recipes/peanut-butter-bonbons.md"
      - "recipes/pumpkin-bars.md"
      - "recipes/roasted-broccoli.md"
      - "recipes/rolf’s-rumaki.md"
      - "recipes/slow-cooker-bbq-pulled-chicken.md"
      - "recipes/spaghetti-sauce.md"
      - "recipes/split-pea-soup.md"
      - "recipes/sticky-buns.md"
      - "recipes/tapioca-surprise.md"
      - "recipes/the-best-pulled-pork-ever.md"
      - "recipes/vanilla-sweet-cream.md"
      - "recipes/veggie-pizza.md"
      - "recipes/whip-cream-salad.md"
      - "recipes/white-chicken-chili.md"
      - "recipes/whole-wheat-bread.md"
      - "recipes/whole-wheat-rolls.md"